--CREATE TABLE ${schema}.concept_reference_type (
--    id varchar(255) PRIMARY KEY NOT NULL
--);
--
--INSERT INTO ${schema}.concept_reference_type (id) VALUES ('broader');
--INSERT INTO ${schema}.concept_reference_type (id) VALUES ('type');
--INSERT INTO ${schema}.concept_reference_type (id) VALUES ('related');
--INSERT INTO ${schema}.concept_reference_type (id) VALUES ('partOf');
--
--CREATE TABLE ${schema}.concept_references AS (
--    SELECT 'broader' AS type_id, concept_id AS source_id, broader_id AS target_id
--      FROM ${schema}.concept_broader
--    UNION ALL
--    SELECT 'type' AS type_id, concept_id AS source_id, type_id AS target_id
--      FROM ${schema}.concept_type
--    UNION ALL
--    SELECT 'related' AS type_id, concept_id AS source_id, related_id AS target_id
--      FROM ${schema}.concept_related
--    UNION ALL
--    SELECT 'type' AS type_id, concept_id AS source_id, part_of_id AS target_id
--      FROM ${schema}.concept_part_of
--);
--
--ALTER TABLE ${schema}.concept_references ADD CONSTRAINT concept_references_type_id_fkey
--    FOREIGN KEY (type_id) REFERENCES ${schema}.concept_reference_type(id);
--ALTER TABLE ${schema}.concept_references ADD CONSTRAINT concept_references_source_id_fkey
--    FOREIGN KEY (source_id) REFERENCES ${schema}.concept(id);
--ALTER TABLE ${schema}.concept_references ADD CONSTRAINT concept_references_target_id_fkey
--    FOREIGN KEY (target_id) REFERENCES ${schema}.concept(id);
--
--CREATE INDEX concept_references_source_id_idx ON ${schema}.concept_references(source_id);
--CREATE INDEX concept_references_target_id_idx ON ${schema}.concept_references(target_id);
